currencies:
  - USD
  - CNY
recipient_limit:
  private_messages: 1
  proposals: 5
group:
  logo:
    gallery:
      width: 690
      height: 450
    full:
      width: 460
      height: 300
    thumb:
      width: 153
      height: 100
    avatar:
      width: 50
      height: 50
startup:
  proposal:
    questions:
      en:
        - Product or service introduction.
        - What is the target market?
        - Please provide an estimated operation margin in 5 years (%).
        - What are the competitors currently in the market?
        - What is the advantage of your product or service?
        - What is your marketing plan?
